#!/bin/bash
#This is a spin off script related to Chadouming's build and package script for Android.
#Created by Evolutionmods & MysteryEmotionz

#Config Section below is where you set your paths-

#Kernel path
kernelDir1="Path to kernel 1" #( Example /home/user/path )
kernelDir2="Path to kernel 2" #( Example /home/user/path )
kernelDir3="Path to kernel 3" #( Example /home/user/path )
#More paths can be added if need be
#Toolchain path
toolchainDir="Path to toolchain" #( Example /home/user/path )
#Path where you would like the kernel to be outputed
exportDir="Path to output folder" #( Example /home/user/Desktop )
#Change default to what ever you like
kernelName="Default" #Change to name of kernel
now=$(date +"%Y-%m-%d")
threads=$(expr 2 + $(grep processor /proc/cpuinfo | wc -l))

# End of Config Section-

clear
echo "                                Kernel-Builder                                 "
echo "                                      By                                       "
echo "                    Chadouming, Evolutionmods & MysteryEmotionz                "
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo " Welcome back" $USER"                      $(date)"
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo 
echo
echo " Please choose a kernel directory"
echo
echo " (1)- Kernel#1"
echo
echo " (2)- Kernel#2"
echo
echo " (3)- Kernel#3"
echo
printf %s " Please Make A Selection: "
echo
read num

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ Kernel#1 ]
then
cd $kernelDir1
fi

if [ Kernel#2 ]
then 
cd $kernelDir2
fi

if [ Kernel#3 ]
then 
cd $kernelDir3
fi

clear
#xxx= Your config name
make ARCH=arm xxx_defconfig
#Change arm-eabi- to what you current toolchain uses default is gcc4.6 & gcc4.7 toolchains
make ARCH=arm CROSS_COMPILE=$toolchainDir/bin/arm-eabi- -j$threads

echo
echo
echo " Done compiling your kernel "

echo
echo
echo " Now the kernel is going to get packaged in a flashable zip"

echo
echo
cp -r $DIR/zip zip2
mv arch/arm/boot/zImage zip2/kernel/
cd zip2
zip -r $kernelName-$now *
mv $kernelName-$now.zip $exportDir
cd ..
rm -r zip2
cd $DIR
echo
echo
echo " Check your output folder"
sleep 60

